// Language configuration file for copy2paste extension
// This file is loaded as a module by i18n.js

const languages = {
  en: {
    title: "copy2paste",
    dragDropText: "Drag and drop your files here",
    supportedFormats:
      "Supported formats: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages, and various code files",
    chooseFiles: "Choose Files",
    copyAll: "Copy All",
    clearAll: "Clear All",
    allTextCopied: "All text copied!",
    allFilesCleared: "All files cleared!",
    noFilesYet: "No files uploaded yet",
    processing: "Processing files...",
    copyright: "© 2025 copy2paste - File Text Extractor | Created with ❤️ by",
    copied: "Copied!",
    light: "Light",
    dark: "Dark",
    system: "System",
    language: "Language",
    // Error messages
    errors: {
      failedToLoad: "Failed to load saved files",
      failedToSave: "Failed to save files",
      failedToCopy: "Failed to copy text to clipboard",
      failedToCopyAll: "Failed to copy all text to clipboard",
      unsupportedFile: "Unsupported file type",
      processingFile: "Error processing file",
      wait: "Please wait for current files to finish processing",
    },
  },
  es: {
    title: "copy2paste",
    dragDropText: "Arrastra y suelta tus archivos aquí",
    supportedFormats:
      "Formatos admitidos: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages y varios archivos de código",
    chooseFiles: "Elegir archivos",
    copyAll: "Copiar todo",
    clearAll: "Borrar todo",
    allTextCopied: "¡Texto copiado!",
    allFilesCleared: "¡Todos los archivos borrados!",
    noFilesYet: "Aún no se han subido archivos",
    processing: "Procesando archivos...",
    copyright:
      "© 2025 copy2paste - Extractor de texto de archivos | Creado con ❤️ por",
    copied: "¡Copiado!",
    light: "Claro",
    dark: "Oscuro",
    system: "Sistema",
    language: "Idioma",
    // Error messages
    errors: {
      failedToLoad: "Error al cargar archivos guardados",
      failedToSave: "Error al guardar archivos",
      failedToCopy: "Error al copiar texto al portapapeles",
      failedToCopyAll: "Error al copiar todo el texto al portapapeles",
      unsupportedFile: "Tipo de archivo no compatible",
      processingFile: "Error al procesar el archivo",
      wait: "Espere a que los archivos actuales terminen de procesarse",
    },
  },
  fr: {
    title: "copy2paste",
    dragDropText: "Glissez et déposez vos fichiers ici",
    supportedFormats:
      "Formats pris en charge: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages et divers fichiers de code",
    chooseFiles: "Choisir des fichiers",
    copyAll: "Tout copier",
    clearAll: "Tout effacer",
    allTextCopied: "Tout le texte copié !",
    allFilesCleared: "Tous les fichiers effacés !",
    noFilesYet: "Aucun fichier téléchargé pour l'instant",
    processing: "Traitement des fichiers...",
    copyright:
      "© 2025 copy2paste - Extracteur de texte de fichier | Créé avec ❤️ par",
    copied: "Copié !",
    light: "Clair",
    dark: "Sombre",
    system: "Système",
    language: "Langue",
    // Error messages
    errors: {
      failedToLoad: "Échec du chargement des fichiers enregistrés",
      failedToSave: "Échec de l'enregistrement des fichiers",
      failedToCopy: "Échec de la copie du texte dans le presse-papiers",
      failedToCopyAll:
        "Échec de la copie de tout le texte dans le presse-papiers",
      unsupportedFile: "Type de fichier non pris en charge",
      processingFile: "Erreur lors du traitement du fichier",
      wait: "Veuillez attendre que les fichiers actuels finissent de traiter",
    },
  },
  de: {
    title: "copy2paste",
    dragDropText: "Ziehen Sie Ihre Dateien hierher",
    supportedFormats:
      "Unterstützte Formate: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages und verschiedene Code-Dateien",
    chooseFiles: "Dateien auswählen",
    copyAll: "Alles kopieren",
    clearAll: "Alles löschen",
    allTextCopied: "Gesamter Text kopiert!",
    allFilesCleared: "Alle Dateien gelöscht!",
    noFilesYet: "Noch keine Dateien hochgeladen",
    processing: "Dateien werden verarbeitet...",
    copyright: "© 2025 copy2paste - Datei-Textextraktor | Erstellt mit ❤️ von",
    copied: "Kopiert!",
    light: "Hell",
    dark: "Dunkel",
    system: "System",
    language: "Sprache",
    // Error messages
    errors: {
      failedToLoad: "Fehler beim Laden gespeicherter Dateien",
      failedToSave: "Fehler beim Speichern von Dateien",
      failedToCopy: "Fehler beim Kopieren von Text in die Zwischenablage",
      failedToCopyAll:
        "Fehler beim Kopieren des gesamten Texts in die Zwischenablage",
      unsupportedFile: "Nicht unterstützter Dateityp",
      processingFile: "Fehler bei der Verarbeitung der Datei",
      wait: "Bitte warten Sie, bis die aktuellen Dateien fertig verarbeitet sind",
    },
  },
  zh: {
    title: "copy2paste",
    dragDropText: "将文件拖放到这里",
    supportedFormats:
      "支持的格式：PDF、DOCX、XLSX、PPTX、TXT、CSV、JSON、Numbers、Pages 和各种代码文件",
    chooseFiles: "选择文件",
    copyAll: "复制全部",
    clearAll: "清除全部",
    allTextCopied: "所有文本已复制！",
    allFilesCleared: "所有文件已清除！",
    noFilesYet: "尚未上传文件",
    processing: "正在处理文件...",
    copyright: "© 2025 copy2paste - 文件文本提取器 | 由 ❤️ 创建",
    copied: "已复制！",
    light: "浅色",
    dark: "深色",
    system: "系统",
    language: "语言",
    // Error messages
    errors: {
      failedToLoad: "无法加载保存的文件",
      failedToSave: "无法保存文件",
      failedToCopy: "无法将文本复制到剪贴板",
      failedToCopyAll: "无法将所有文本复制到剪贴板",
      unsupportedFile: "不支持的文件类型",
      processingFile: "处理文件时出错",
      wait: "请等待当前文件处理完成",
    },
  },
  ja: {
    title: "copy2paste",
    dragDropText: "ここにファイルをドラッグ＆ドロップ",
    supportedFormats:
      "対応フォーマット: PDF、DOCX、XLSX、PPTX、TXT、CSV、JSON、Numbers、Pages、各種コードファイル",
    chooseFiles: "ファイルを選択",
    copyAll: "全てコピー",
    clearAll: "全て削除",
    allTextCopied: "全テキストがコピーされました！",
    allFilesCleared: "全てのファイルが削除されました！",
    noFilesYet: "ファイルはまだアップロードされていません",
    processing: "ファイル処理中...",
    copyright: "© 2025 copy2paste - ファイルテキスト抽出ツール | ❤️ で作成",
    copied: "コピー完了！",
    light: "ライト",
    dark: "ダーク",
    system: "システム",
    language: "言語",
    errors: {
      failedToLoad: "保存されたファイルの読み込みに失敗しました",
      failedToSave: "ファイルの保存に失敗しました",
      failedToCopy: "テキストのクリップボードへのコピーに失敗しました",
      failedToCopyAll: "すべてのテキストのコピーに失敗しました",
      unsupportedFile: "サポートされていないファイル形式です",
      processingFile: "ファイル処理中にエラーが発生しました",
      wait: "現在のファイルの処理が完了するまでお待ちください",
    },
  },
  ko: {
    title: "copy2paste",
    dragDropText: "여기에 파일을 끌어다 놓으세요",
    supportedFormats:
      "지원 형식: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages 및 다양한 코드 파일",
    chooseFiles: "파일 선택",
    copyAll: "모두 복사",
    clearAll: "모두 지우기",
    allTextCopied: "모든 텍스트가 복사되었습니다!",
    allFilesCleared: "모든 파일이 지워졌습니다!",
    noFilesYet: "아직 업로드된 파일이 없습니다",
    processing: "파일 처리 중...",
    copyright: "© 2025 copy2paste - 파일 텍스트 추출기 | ❤️로 제작",
    copied: "복사 완료!",
    light: "라이트",
    dark: "다크",
    system: "시스템",
    language: "언어",
    errors: {
      failedToLoad: "저장된 파일을 불러오지 못했습니다",
      failedToSave: "파일 저장에 실패했습니다",
      failedToCopy: "텍스트를 클립보드에 복사하지 못했습니다",
      failedToCopyAll: "모든 텍스트 복사에 실패했습니다",
      unsupportedFile: "지원되지 않는 파일 유형입니다",
      processingFile: "파일 처리 중 오류가 발생했습니다",
      wait: "현재 파일 처리가 완료될 때까지 기다려주세요",
    },
  },
  pt: {
    title: "copy2paste",
    dragDropText: "Arraste e solte seus arquivos aqui",
    supportedFormats:
      "Formatos suportados: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages e vários arquivos de código",
    chooseFiles: "Escolher arquivos",
    copyAll: "Copiar tudo",
    clearAll: "Limpar tudo",
    allTextCopied: "Todo o texto copiado!",
    allFilesCleared: "Todos os arquivos removidos!",
    noFilesYet: "Nenhum arquivo enviado ainda",
    processing: "Processando arquivos...",
    copyright:
      "© 2025 copy2paste - Extrator de Texto de Arquivos | Criado com ❤️ por",
    copied: "Copiado!",
    light: "Claro",
    dark: "Escuro",
    system: "Sistema",
    language: "Idioma",
    errors: {
      failedToLoad: "Falha ao carregar arquivos salvos",
      failedToSave: "Falha ao salvar arquivos",
      failedToCopy: "Falha ao copiar texto para a área de transferência",
      failedToCopyAll: "Falha ao copiar todo o texto",
      unsupportedFile: "Tipo de arquivo não suportado",
      processingFile: "Erro ao processar arquivo",
      wait: "Aguarde a conclusão do processamento dos arquivos atuais",
    },
  },
  ru: {
    title: "copy2paste",
    dragDropText: "Перетащите файлы сюда",
    supportedFormats:
      "Поддерживаемые форматы: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages и различные файлы кода",
    chooseFiles: "Выбрать файлы",
    copyAll: "Копировать всё",
    allTextCopied: "Весь текст скопирован!",
    noFilesYet: "Файлы ещё не загружены",
    processing: "Обработка файлов...",
    copyright: "© 2025 copy2paste - Извлечение текста из файлов | Создано с ❤️",
    copied: "Скопировано!",
    light: "Светлая",
    dark: "Тёмная",
    system: "Системная",
    language: "Язык",
    errors: {
      failedToLoad: "Не удалось загрузить сохраненные файлы",
      failedToSave: "Не удалось сохранить файлы",
      failedToCopy: "Не удалось скопировать текст в буфер обмена",
      failedToCopyAll: "Не удалось скопировать весь текст",
      unsupportedFile: "Неподдерживаемый тип файла",
      processingFile: "Ошибка при обработке файла",
      wait: "Дождитесь завершения обработки текущих файлов",
    },
  },
  hi: {
    title: "copy2paste",
    dragDropText: "अपनी फ़ाइलें यहां खींचें और छोड़ें",
    supportedFormats:
      "समर्थित प्रारूप: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages और विभिन्न कोड फ़ाइलें",
    chooseFiles: "फ़ाइलें चुनें",
    copyAll: "सभी कॉपी करें",
    allTextCopied: "सभी टेक्स्ट कॉपी किया गया!",
    noFilesYet: "अभी तक कोई फ़ाइल अपलोड नहीं की गई",
    processing: "फ़ाइलें प्रोसेस हो रही हैं...",
    copyright:
      "© 2025 copy2paste - फ़ाइल टेक्स्ट एक्सट्रैक्टर | ❤️ के साथ बनाया गया",
    copied: "कॉपी किया गया!",
    light: "लाइट",
    dark: "डार्क",
    system: "सिस्टम",
    language: "भाषा",
    errors: {
      failedToLoad: "सहेजी गई फ़ाइलें लोड करने में विफल",
      failedToSave: "फ़ाइलें सहेजने में विफल",
      failedToCopy: "टेक्स्ट को क्लिपबोर्ड पर कॉपी करने में विफल",
      failedToCopyAll: "सभी टेक्स्ट कॉपी करने में विफल",
      unsupportedFile: "असमर्थित फ़ाइल प्रकार",
      processingFile: "फ़ाइल प्रोसेसिंग में त्रुटि",
      wait: "कृपया वर्तमान फ़ाइलों की प्रोसेसिंग पूरी होने तक प्रतीक्षा करें",
    },
  },
  ar: {
    title: "copy2paste",
    dragDropText: "اسحب وأفلت الملفات هنا",
    supportedFormats:
      "التنسيقات المدعومة: PDF، DOCX، XLSX، PPTX، TXT، CSV، JSON، Numbers، Pages وملفات الكود المختلفة",
    chooseFiles: "اختر الملفات",
    copyAll: "نسخ الكل",
    allTextCopied: "تم نسخ كل النص!",
    noFilesYet: "لم يتم تحميل أي ملفات بعد",
    processing: "جاري معالجة الملفات...",
    copyright: "© 2025 copy2paste - مستخرج نص الملفات | تم إنشاؤه بواسطة ❤️",
    copied: "تم النسخ!",
    light: "فاتح",
    dark: "داكن",
    system: "النظام",
    language: "اللغة",
    errors: {
      failedToLoad: "فشل في تحميل الملفات المحفوظة",
      failedToSave: "فشل في حفظ الملفات",
      failedToCopy: "فشل في نسخ النص إلى الحافظة",
      failedToCopyAll: "فشل في نسخ كل النص",
      unsupportedFile: "نوع ملف غير مدعوم",
      processingFile: "خطأ في معالجة الملف",
      wait: "يرجى الانتظار حتى تكتمل معالجة الملفات الحالية",
    },
  },
  it: {
    title: "copy2paste",
    dragDropText: "Trascina e rilascia i tuoi file qui",
    supportedFormats:
      "Formati supportati: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages e vari file di codice",
    chooseFiles: "Scegli file",
    copyAll: "Copia tutto",
    allTextCopied: "Tutto il testo copiato!",
    noFilesYet: "Nessun file caricato",
    processing: "Elaborazione dei file in corso...",
    copyright:
      "© 2025 copy2paste - Estrattore di testo da file | Creato con ❤️ da",
    copied: "Copiato!",
    light: "Chiaro",
    dark: "Scuro",
    system: "Sistema",
    language: "Lingua",
    errors: {
      failedToLoad: "Impossibile caricare i file salvati",
      failedToSave: "Impossibile salvare i file",
      failedToCopy: "Impossibile copiare il testo negli appunti",
      failedToCopyAll: "Impossibile copiare tutto il testo",
      unsupportedFile: "Tipo di file non supportato",
      processingFile: "Errore durante l'elaborazione del file",
      wait: "Attendi il completamento dell'elaborazione dei file correnti",
    },
  },
  tr: {
    title: "copy2paste",
    dragDropText: "Dosyalarınızı buraya sürükleyip bırakın",
    supportedFormats:
      "Desteklenen formatlar: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages ve çeşitli kod dosyaları",
    chooseFiles: "Dosya Seç",
    copyAll: "Tümünü Kopyala",
    allTextCopied: "Tüm metin kopyalandı!",
    noFilesYet: "Henüz dosya yüklenmedi",
    processing: "Dosyalar işleniyor...",
    copyright: "© 2025 copy2paste - Dosya Metin Çıkarıcı | ❤️ ile oluşturuldu",
    copied: "Kopyalandı!",
    light: "Açık",
    dark: "Koyu",
    system: "Sistem",
    language: "Dil",
    errors: {
      failedToLoad: "Kaydedilen dosyalar yüklenemedi",
      failedToSave: "Dosyalar kaydedilemedi",
      failedToCopy: "Metin panoya kopyalanamadı",
      failedToCopyAll: "Tüm metin kopyalanamadı",
      unsupportedFile: "Desteklenmeyen dosya türü",
      processingFile: "Dosya işlenirken hata oluştu",
      wait: "Lütfen mevcut dosyaların işlenmesi bitene kadar bekleyin",
    },
  },
  nl: {
    title: "copy2paste",
    dragDropText: "Sleep je bestanden hierheen",
    supportedFormats:
      "Ondersteunde formaten: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages en verschillende codebestanden",
    chooseFiles: "Bestanden kiezen",
    copyAll: "Alles kopiëren",
    allTextCopied: "Alle tekst gekopieerd!",
    noFilesYet: "Nog geen bestanden geüpload",
    processing: "Bestanden verwerken...",
    copyright:
      "© 2025 copy2paste - Bestandstekst Extractor | Gemaakt met ❤️ door",
    copied: "Gekopieerd!",
    light: "Licht",
    dark: "Donker",
    system: "Systeem",
    language: "Taal",
    errors: {
      failedToLoad: "Kan opgeslagen bestanden niet laden",
      failedToSave: "Kan bestanden niet opslaan",
      failedToCopy: "Kan tekst niet naar klembord kopiëren",
      failedToCopyAll: "Kan niet alle tekst kopiëren",
      unsupportedFile: "Niet-ondersteund bestandstype",
      processingFile: "Fout bij verwerken van bestand",
      wait: "Wacht tot de huidige bestanden zijn verwerkt",
    },
  },
  bn: {
    title: "copy2paste",
    dragDropText: "আপনার ফাইলগুলি এখানে টেনে আনুন",
    supportedFormats:
      "সমর্থিত ফরম্যাট: PDF, DOCX, XLSX, PPTX, TXT, CSV, JSON, Numbers, Pages এবং বিভিন্ন কোড ফাইল",
    chooseFiles: "ফাইল বেছে নিন",
    copyAll: "সব কপি করুন",
    allTextCopied: "সমস্ত টেক্সট কপি করা হয়েছে!",
    noFilesYet: "এখনো কোনো ফাইল আপলোড করা হয়নি",
    processing: "ফাইল প্রক্রিয়াকরণ চলছে...",
    copyright:
      "© 2025 copy2paste - ফাইল টেক্সট এক্সট্রাক্টর | ❤️ দিয়ে তৈরি করেছেন",
    copied: "কপি করা হয়েছে!",
    light: "হালকা",
    dark: "গাঢ়",
    system: "সিস্টেম",
    language: "ভাষা",
    errors: {
      failedToLoad: "সংরক্ষিত ফাইল লোড করতে ব্যর্থ",
      failedToSave: "ফাইল সংরক্ষণ করতে ব্যর্থ",
      failedToCopy: "ক্লিপবোর্ডে টেক্সট কপি করতে ব্যর্থ",
      failedToCopyAll: "সমস্ত টেক্সট কপি করতে ব্যর্থ",
      unsupportedFile: "অসমর্থিত ফাইল টাইপ",
      processingFile: "ফাইল প্রক্রিয়াকরণে ত্রুটি",
      wait: "অনুগ্রহ করে বর্তমান ফাইলগুলি প্রক্রিয়াকরণ শেষ হওয়া পর্যন্ত অপেক্ষা করুন",
    },
  },
};

// Get browser language or default to English
function getDefaultLanguage() {
  const browserLang = navigator.language.split("-")[0];
  return languages[browserLang] ? browserLang : "en";
}

export { languages, getDefaultLanguage };
